title: EavesDrum
github:
  repository_url: https://github.com/tobigun/EavesDrum
remote_theme: "jekyll/minima@b3385fe64e9d79e75260668cad1852a3913b1829"
markdown: kramdown
plugins_dir: doc/_plugins
includes_dir: doc/_includes
plugins:
  - jekyll-remote-theme
  - jekyll-gfm-admonitions  
  - jekyll-readme-index
exclude:
  - webui
  - lib
  - src
  - .pio
  - doc/schematics/**/*.md
minima:
  skin: dark
  hide_site_feed_link: true
readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true
# set default layout to minima's home layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: home
