# yaml-language-server: $schema=./config.jsonc
mappings:
  Snare:
    noteMain: 38
    noteRim: 40
    noteCross: 76
  Tom1:
    noteMain: 48
    noteRim: 81
    noteCross: 74
  Tom2:
    noteMain: 47
    noteRim: 79
    noteCross: 77
  Tom3:
    noteMain: 45
    noteRim: 77
    noteCross: 79
  Kick:
    noteMain: 36
  Ride:
    noteMain: 51
    noteRim: 52
    noteCup: 53
  Crash1:
    noteMain: 84
    noteRim: 86
    noteCup: 0
  Crash2:
    noteMain: 84
    noteRim: 86
    noteCup: 0
  Hi-Hat:
    closedNotesEnabled: false
    noteMain: 19
    noteCloseMain: 0
    noteRim: 18
    noteCloseRim: 0
    noteCup: 0
    noteCloseCup: 0
  Hi-Hat Pedal:
    pedalChickEnabled: true
    noteMain: 21
