mappings:
  Snare: 
    noteMain: 38
    noteRim: 40
    crossNoteEnabled: false
    noteCross: 76
  Tom 1: 
    noteMain: 43
    noteRim: 75
    crossNoteEnabled: false
    noteCross: 74
  Tom 2: 
    noteMain: 45
    noteRim: 78
    crossNoteEnabled: false
    noteCross: 77
  Tom 3: 
    noteMain: 47
    noteRim: 80
    crossNoteEnabled: false
    noteCross: 79
  Kick: 
    noteMain: 47
  Hi-Hat: 
    closedNotesEnabled: true
    noteMain: 8
    noteCloseMain: 0
    noteRim: 17
    noteCloseRim: 9
    noteCup: 26
    noteCloseCup: 18
  Hi-Hat Pedal: 
    pedalChickEnabled: true
    noteMain: 32
  Crash: 
    noteMain: 84
    noteRim: 86
  Ride: 
    noteMain: 51
    noteRim: 52
    noteCup: 53