settings:
  padType: Drum
  zonesType: Zones3_Piezos
  curveType: Linear
  scanTimeUs: 3000
  maskTimeMs: 30
  zoneThresholds: 
    - min: 110
      max: 894
    - min: 47
      max: 292
    - min: 102
      max: 781
