settings:
  padType: Drum
  zonesType: Zones3_Piezos
  curveType: Linear
  scanTimeUs: 3000
  maskTimeMs: 30
  zoneThresholds:
    - min: 102
      max: 670
    - min: 102
      max: 572
    - min: 102
      max: 636
  headRimBias: 25
  