settings:
  padType: Drum
  zonesType: Zones2_Piezos
  curveType: Linear
  scanTimeUs: 3000
  maskTimeMs: 30
  zoneThresholds:
    - min: 61
      max: 614
    - min: 164
      max: 614
  headRimBias: 0
