# yaml-language-server: $schema=https://raw.githubusercontent.com/tobigun/EavesDrum/refs/tags/config-schema-v1.0/config/config.jsonc
general:
  gateTimeMs: 0
mux:
  - type: HC4067
    pins:
      analogIn: 26
      enable: 10
      select:
        - 6
        - 7
        - 8
        - 9
  - type: HC4067
    pins:
      analogIn: 26
      enable: 15
      select:
        - 11
        - 12
        - 13
        - 14
connectors:
  Jack1:
    pins:
      - mux: 0
        channel: 0
      - mux: 0
        channel: 1
      - mux: 0
        channel: 2
  Jack2:
    pins:
      - mux: 0
        channel: 3
      - mux: 0
        channel: 4
  Jack3:
    pins:
      - mux: 0
        channel: 5
      - mux: 0
        channel: 6
  Jack4:
    pins:
      - mux: 0
        channel: 7
      - mux: 0
        channel: 8
  Jack5:
    pins:
      - mux: 0
        channel: 9
  Jack6:
    pins:
      - mux: 0
        channel: 10
      - mux: 0
        channel: 11
      - mux: 0
        channel: 12
  Jack7:
    pins:
      - mux: 0
        channel: 13
      - mux: 0
        channel: 14
      - mux: 0
        channel: 15
  Jack8:
    pins:
      - mux: 1
        channel: 0
      - mux: 1
        channel: 1
      - mux: 1
        channel: 2
  Jack9:
    pins:
      - mux: 1
        channel: 3
      - mux: 1
        channel: 4
      - mux: 1
        channel: 5
  Jack10:
    pins:
      - mux: 1
        channel: 6
      - mux: 1
        channel: 7
      - mux: 1
        channel: 8
  Jack11:
    pins:
      - mux: 1
        channel: 9
      - mux: 1
        channel: 10
  Jack12:
    pins:
      - mux: 1
        channel: 11
      - mux: 1
        channel: 12
  Jack13:
    pins:
      - mux: 1
        channel: 13
      - mux: 1
        channel: 14
      - mux: 1
        channel: 15
  Jack-Pedal:
    pins:
      - 28
pads:
  - name: Snare
    role: Snare
    enabled: true
    settings:
      padType: Drum
      zonesType: Zones3_Piezos
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 102
          max: 670
        - min: 102
          max: 572
        - min: 102
          max: 636
      headRimBias: 25
    connector: Jack1
  - name: Tom 1
    role: Tom1
    group: Toms
    enabled: true
    settings:
      padType: Drum
      zonesType: Zones2_Piezos
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 61
          max: 614
        - min: 164
          max: 614
      crossNoteEnabled: false
      headRimBias: 0
    connector: Jack2
  - name: Tom 2
    role: Tom2
    group: Toms
    enabled: true
    settings:
      padType: Drum
      zonesType: Zones2_Piezos
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 61
          max: 614
        - min: 164
          max: 614
      crossNoteEnabled: false
      headRimBias: 0
    connector: Jack3
  - name: Tom 3
    role: Tom3
    group: Toms
    enabled: true
    settings:
      padType: Drum
      zonesType: Zones2_Piezos
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 51
          max: 614
        - min: 31
          max: 256
      crossNoteEnabled: false
      headRimBias: 10
    connector: Jack4
  - name: Tom 4
    role: Tom4
    group: Toms
    enabled: false
    settings:
      padType: Drum
      zonesType: Zones2_Piezos
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 511
          max: 1023
        - min: 258
          max: 1023
      crossNoteEnabled: false
      headRimBias: 0
    connector: Jack11
  - name: Tom 5
    role: Tom5
    group: Toms
    enabled: false
    settings:
      padType: Drum
      zonesType: Zones2_Piezos
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 511
          max: 1023
        - min: 258
          max: 1023
      crossNoteEnabled: false
      headRimBias: 0
    connector: Jack12
  - name: Kick
    role: Kick
    enabled: true
    settings:
      padType: Drum
      zonesType: Zones1_Piezo
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 102
          max: 614
    connector: Jack5
  - name: Ride
    role: Ride1
    group: Cymbals
    enabled: true
    settings:
      padType: Cymbal
      zonesType: Zones3_PiezoAndSwitches_2TRS
      chokeType: Switch_Edge
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 31
          max: 358
        - min: 307
        - min: 307
    connector: Jack6
  - name: Cymbal 1
    role: Cymbal1
    group: Cymbals
    enabled: true
    settings:
      padType: Cymbal
      zonesType: Zones3_PiezoAndSwitches_2TRS
      chokeType: Switch_Edge
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 31
          max: 409
        - min: 307
        - min: 307
    connector: Jack7
  - name: Cymbal 2
    role: Cymbal2
    group: Cymbals
    enabled: true
    settings:
      padType: Cymbal
      zonesType: Zones3_PiezoAndSwitches_2TRS
      chokeType: Switch_Edge
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 51
          max: 563
        - min: 307
        - min: 307
    connector: Jack8
  - name: Cymbal 3
    role: Cymbal3
    group: Cymbals
    enabled: false
    settings:
      padType: Cymbal
      zonesType: Zones3_PiezoAndSwitches_2TRS
      chokeType: Switch_Edge
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 110
          max: 670
        - min: 273
        - min: 511
    connector: Jack9
  - name: Cymbal 4
    role: Cymbal4
    group: Cymbals
    enabled: false
    settings:
      padType: Cymbal
      zonesType: Zones3_PiezoAndSwitches_2TRS
      chokeType: Switch_Edge
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 110
          max: 670
        - min: 273
        - min: 511
    connector: Jack13
  - name: Hi-Hat
    role: HiHat
    enabled: true
    settings:
      padType: Cymbal
      zonesType: Zones3_PiezoAndSwitches_2TRS
      chokeType: Switch_Edge
      curveType: Linear
      scanTimeUs: 3000
      maskTimeMs: 30
      zoneThresholds:
        - min: 31
          max: 307
        - min: 307
        - min: 307
    pedal: Hi-Hat Pedal
    connector: Jack10
  - name: Hi-Hat Pedal
    role: HiHat-Pedal
    enabled: true
    settings:
      padType: Pedal
      zonesType: Zones1_Controller
      zoneThresholds:
        - min: 205
          max: 819
      almostClosedThreshold: 70
      closedThreshold: 85
      moveDetectTolerance: 20
      chickDetectTimeoutMs: 20
      curveType: Linear
    connector: Jack-Pedal
mappings:
  Snare:
    noteMain: 38
    noteRim: 40
    noteCross: 37
  Tom1:
    name: Rack Tom 1
    noteMain: 48
    noteRim: 82
    noteCross: 81
  Tom2:
    name: Rack Tom 2
    noteMain: 47
    noteRim: 80
    noteCross: 79
  Tom3:
    name: Rack Tom 3
    noteMain: 45
    noteRim: 78
    noteCross: 77
  Tom4:
    name: Floor Tom 1
    noteMain: 43
    noteRim: 75
    noteCross: 74
  Tom5:
    name: Floor Tom 2
    noteMain: 41
    noteRim: 73
    noteCross: 72
  Kick:
    noteMain: 36
  HiHat:
    name: Hi-Hat
    noteMain: 19
    noteRim: 7
    noteCup: 53
    closedNotesEnabled: false
    noteCloseMain: 11
    noteCloseRim: 22
    noteCloseCup: 53
  HiHat-Pedal:
    name: Hi-Hat Pedal
    noteMain: 21
  Ride1:
    name: Ride
    noteMain: 51
    noteRim: 52
    noteCup: 53
  Cymbal1:
    name: Crash 1
    noteMain: 87
    noteRim: 86
    noteCup: 53
  Cymbal2:
    name: Crash 2
    noteMain: 27
    noteRim: 28
    noteCup: 53
  Cymbal3:
    name: Crash 3
    noteMain: 31
    noteRim: 32
    noteCup: 53
  Cymbal4:
    name: Crash 4
    noteMain: 96
    noteRim: 98
    noteCup: 5
  Effect1:
    name: Tambourine / Shaker / One Shot
    noteMain: 3
    noteRim: 2
    noteCup: 1
